
title: Skandan C Yalagach | Systems Engineer in training
description: From Basic ML Math to Fast Code.
baseurl: ""
url: "https://skandanyal.github.io"
these: null

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - metadata.json
  - index.tsx
  - App.tsx
  - data.ts
  - types.ts
  - components/

